services:
  db-link-friend:
    container_name: db-link-friend
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
      
  app:
    build:
      context: .
      dockerfile: dockerfile
    command: sh -c "npm run migration:generate:auto && npm run migration:run && npm run start:dev"
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db-link-friend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      REDIS_PORT: ${REDIS_PORT}
      LOG_LEVEL: ${LOG_LEVEL}

volumes:
  db_data:
